/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.UIS.Admin.Academic_Manager;

import deu.UIS.Admin.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YangJinWon
 */
public class A_Management extends javax.swing.JFrame {

    private static final String FILE_PATH = Paths.get(System.getProperty("user.home"), "data", "Academic_info.txt").toString();
    private final DefaultTableModel tableModel;

    /**
     * Creates new form Academic_Management
     */
    public A_Management() {
        initComponents();
        tableModel = (DefaultTableModel) S_list.getModel();
        loadAcademicInfo(); // 데이터를 파일에서 불러오기
        addMouseListenerToSList(); // 테이블에 MouseListener 추가
    }
    // 학생 정보를 파일에서 불러와 테이블에 추가하는 메서드

    private void loadAcademicInfo() {
        List<AcademicInfo> academicInfoList = readAcademicInfoFromFile();
        tableModel.setRowCount(0); // 기존 데이터 초기화

        for (AcademicInfo info : academicInfoList) {
            tableModel.addRow(new Object[]{
                info.getName(),
                info.getAcademicNumber(),
                info.getBirthDate(),
                info.getPhone() // 비밀번호 제외
            });
        }
    }

    private void addMouseListenerToSList() {
        S_list.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int selectedRow = S_list.getSelectedRow();
                if (selectedRow != -1) {
                    String selectedName = (String) S_list.getValueAt(selectedRow, 0);
                    String selectedAcademicNumber = (String) S_list.getValueAt(selectedRow, 1);

                    populateAcademicDetails(selectedAcademicNumber, selectedName);
                }
            }
        });
    }

    private void populateAcademicDetails(String academicNumber, String name) {
        List<AcademicInfo> academicInfoList = readAcademicInfoFromFile();

        DefaultTableModel infoModel = new DefaultTableModel(
                new String[]{"이름", "학사담당자번호", "생년월일", "휴대폰"}, 0);
        S_info.setModel(infoModel);

        for (AcademicInfo info : academicInfoList) {
            if (info.getAcademicNumber().equals(academicNumber) && info.getName().equals(name)) {
                infoModel.addRow(new Object[]{
                    info.getName(),
                    info.getAcademicNumber(),
                    info.getBirthDate(),
                    info.getPhone() // 비밀번호 제외
                });
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        birthdate = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numberBox = new javax.swing.JComboBox<>();
        Name = new javax.swing.JTextField();
        birth = new javax.swing.JTextField();
        birthlast = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        S_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        search_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        Before = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        S_list = new javax.swing.JTable();
        Delete = new javax.swing.JButton();
        modify = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        S_info = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        save = new javax.swing.JButton();
        info_refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        Title.setText("학사담당자 관리 페이지");

        title.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        title.setText("학사담당자 정보 입력");

        name.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        name.setText("이름");

        birthdate.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        birthdate.setText("주민등록번호");

        phone.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        phone.setText("휴대폰");

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        jLabel1.setText("학사담당자 정보 검색");

        numberBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "학사담당자번호", "이름" }));
        numberBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBoxActionPerformed(evt);
            }
        });

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        birth.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        birth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthActionPerformed(evt);
            }
        });

        birthlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthlastActionPerformed(evt);
            }
        });

        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });

        S_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_searchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        jLabel2.setText("학사담당자 정보");

        search_button.setText("검색");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        jLabel3.setText("학사담당자 목록");

        Add.setText("추가");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Before.setText("이전");
        Before.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeforeActionPerformed(evt);
            }
        });

        S_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "이름", "학사담당자번호"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(S_list);

        Delete.setText("삭제");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        modify.setText("수정");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });

        S_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "이름", "학사담당자번호", "주민등록번호", "휴대폰"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(S_info);

        refresh.setText("새로고침");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        save.setText("저장");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        info_refresh.setText("새로고침");
        info_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(birthdate, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(phone))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(birth, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(birthlast))
                                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(title)
                            .addComponent(name)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Before)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(refresh))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(numberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(S_search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(modify)
                                .addGap(18, 18, 18)
                                .addComponent(save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Delete)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(info_refresh)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(Title)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthdate)
                            .addComponent(birthlast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Add)
                            .addComponent(Before)
                            .addComponent(modify)
                            .addComponent(save)
                            .addComponent(Delete)
                            .addComponent(info_refresh)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(S_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(search_button)
                                .addComponent(numberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(refresh))
                            .addGap(11, 11, 11)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void numberBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberBoxActionPerformed

    private void S_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S_searchActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        String keyword = S_search.getText().trim(); // 검색 필드에서 키워드 가져오기
        String searchType = (String) numberBox.getSelectedItem(); // numberBox에서 선택된 값 가져오기

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "검색어를 입력해주세요.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String filePath = Paths.get(System.getProperty("user.home"), "data", "Academic_info.txt").toString();
        DefaultTableModel model = (DefaultTableModel) S_list.getModel();
        model.setRowCount(0); // 테이블 초기화

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            String studentNumber = "", name = "";

            while ((line = reader.readLine()) != null) {
                line = line.trim();

                if (line.startsWith("학사담당자번호: ")) {
                    studentNumber = line.substring(8).trim(); // "학사담당자번호: " 이후 값 추출
                } else if (line.startsWith("이름: ")) {
                    name = line.substring(4).trim(); // "이름: " 이후 값 추출
                } else if (line.isEmpty() && !studentNumber.isEmpty() && !name.isEmpty()) {
                    // 검색 타입에 따라 매칭
                    boolean matches = false;
                    if ("학사담당자번호".equals(searchType)) {
                        matches = keyword.equals(studentNumber); // 학사담당자번호 매칭
                    } else if ("이름".equals(searchType)) {
                        matches = keyword.equalsIgnoreCase(name); // 이름 매칭 (대소문자 무시)
                    }

                    if (matches) {
                        model.addRow(new Object[]{name, studentNumber});
                    }

                    // 데이터 초기화
                    studentNumber = "";
                    name = "";
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "학사 담당자 정보 검색 중 오류가 발생했습니다.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // 검색 결과가 없을 경우 알림
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "검색 결과가 없습니다.", "검색", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_search_buttonActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        String name = Name.getText().trim();
        String phone = Phone.getText().trim();
        String birthFirst = birth.getText().trim();
        String birthLast = birthlast.getText().trim();
        String birthDate = birthFirst + "-" + birthLast;

        try {
            //AcademicValidator를 통해 입력값의 유효성을 검증
            AcademicValidator.validateInput(name, phone, birthDate);

            List<AcademicInfo> academicInfoList = readAcademicInfoFromFile();
            String newAcademicNumber = generateNewAcademicNumber(academicInfoList);

            AcademicInfo newInfo = new AcademicInfo(name, newAcademicNumber, birthDate, phone);
            academicInfoList.add(newInfo);
            saveAcademicInfoToFile(academicInfoList);

            tableModel.addRow(new Object[]{name, newAcademicNumber, birthDate, phone});
            clearInputFields();

            JOptionPane.showMessageDialog(this, "학사담당자 정보가 저장되었습니다.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddActionPerformed

    private void BeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeforeActionPerformed
        // TODO add your handling code here:
        dispose();
        new Admin_Main().setVisible(true);
    }//GEN-LAST:event_BeforeActionPerformed

    private void birthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        int selectedRow = S_list.getSelectedRow();

        if (selectedRow != -1) {
            String selectedAcademicNumber = (String) S_list.getValueAt(selectedRow, 1);

            List<AcademicInfo> academicInfoList = readAcademicInfoFromFile();
            academicInfoList.removeIf(info -> info.getAcademicNumber().equals(selectedAcademicNumber));
            saveAcademicInfoToFile(academicInfoList);

            tableModel.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "선택된 학사담당자 정보가 삭제되었습니다.");
        } else {
            JOptionPane.showMessageDialog(this, "삭제할 학사담당자를 선택해주세요.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        // 선택된 학생 정보가 없으면 경고 메시지
        int selectedRow = S_list.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "수정할 학사 담당자를 선택해주세요.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // 선택된 행에서 기본 정보를 가져옵니다.
        String selectedName = (String) S_list.getValueAt(selectedRow, 0);         // 이름
        String selectedStudentNumber = (String) S_list.getValueAt(selectedRow, 1); // 학사 담당자 번호

        // 파일에서 선택된 학생의 세부 정보를 가져와서 입력 필드에 채웁니다.
        String filePath = Paths.get(System.getProperty("user.home"), "data", "Academic_info.txt").toString();

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            String studentNumber = "", name = "", birthDate = "", phone = "";

            while ((line = reader.readLine()) != null) {
                line = line.trim();

                if (line.startsWith("학사담당자번호: ")) {
                    studentNumber = line.substring(8).trim(); // 공백 제거 포함
                } else if (line.startsWith("이름: ")) {
                    name = line.substring(4);
                } else if (line.startsWith("생년월일: ")) {
                    birthDate = line.substring(6);
                } else if (line.startsWith("휴대폰: ")) {
                    phone = line.substring(5);
                } else if (line.isEmpty() && name.equals(selectedName) && studentNumber.equals(selectedStudentNumber)) {
                    // 선택된 학생과 일치하는 정보를 찾았을 때 입력 필드에 채우기
                    Name.setText(name);

                    // 주민등록번호를 앞 6자리와 뒤 7자리로 나눔
                    if (birthDate.length() == 14) { // 주민등록번호 형식 확인 (앞 6 + "-" + 뒤 7)
                        String[] parts = birthDate.split("-");
                        if (parts.length == 2) {
                            birth.setText(parts[0]);     // 앞 6자리
                            birthlast.setText(parts[1]); // 뒤 7자리
                        }
                    } else {
                        birth.setText(birthDate); // 형식이 맞지 않을 경우 전체 입력
                    }

                    Phone.setText(phone);
                    break;
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "학사 담당자 정보를 불러오는 중 오류가 발생했습니다.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modifyActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // 학생 정보를 다시 불러와서 S_list 테이블을 새로 갱신합니다.
        loadAcademicInfo();
    }//GEN-LAST:event_refreshActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        int selectedRow = S_list.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "저장할 학사담당자를 선택해주세요.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 입력 필드에서 수정된 데이터 가져오기
        String updatedName = Name.getText().trim();
        String updatedPhone = Phone.getText().trim();
        String birthFirst = birth.getText().trim();
        String birthLast = birthlast.getText().trim();
        String updatedBirthDate = birthFirst + "-" + birthLast;
        String existingAcademicNumber = (String) S_list.getValueAt(selectedRow, 1); // 선택된 학사 담당자 번호

        try {
            // 입력 값 검증
            AcademicValidator.validateInput(updatedName, updatedPhone, updatedBirthDate);

            // 파일에서 데이터 읽기
            List<AcademicInfo> academicInfoList = readAcademicInfoFromFile();
            boolean isUpdated = false;

            for (int i = 0; i < academicInfoList.size(); i++) {
                AcademicInfo info = academicInfoList.get(i);
                if (info.getAcademicNumber().equals(existingAcademicNumber)) {
                    // 수정된 데이터로 갱신
                    academicInfoList.set(i, new AcademicInfo(updatedName, existingAcademicNumber, updatedBirthDate, updatedPhone));
                    isUpdated = true;
                    break;
                }
            }

            if (!isUpdated) {
                JOptionPane.showMessageDialog(this, "수정할 학사 담당자 정보를 찾을 수 없습니다.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 파일에 수정된 데이터 저장
            saveAcademicInfoToFile(academicInfoList);

            // 테이블 갱신
            loadAcademicInfo();

            // 성공 메시지
            JOptionPane.showMessageDialog(this, "학사 담당자 정보가 성공적으로 수정되었습니다.");

            // 입력 필드 초기화
            clearInputFields();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveActionPerformed
    private List<AcademicInfo> readAcademicInfoFromFile() {
        List<AcademicInfo> academicInfoList = new ArrayList<>();
        try (BufferedReader reader = new BufferedReader(new FileReader(FILE_PATH))) {
            String line, name = "", academicNumber = "", birthDate = "", phone = "";

            while ((line = reader.readLine()) != null) {
                line = line.trim();
                if (line.startsWith("학사담당자번호: ")) {
                    academicNumber = line.substring(8).trim();
                } else if (line.startsWith("이름: ")) {
                    name = line.substring(4).trim();
                } else if (line.startsWith("생년월일: ")) {
                    birthDate = line.substring(6).trim();
                } else if (line.startsWith("휴대폰: ")) {
                    phone = line.substring(5).trim();
                } else if (line.isEmpty() && !name.isEmpty() && !academicNumber.isEmpty() && !birthDate.isEmpty() && !phone.isEmpty()) {
                    academicInfoList.add(new AcademicInfo(name, academicNumber, birthDate, phone));
                    name = academicNumber = birthDate = phone = "";
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 읽기 오류: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return academicInfoList;
    }

    private void saveAcademicInfoToFile(List<AcademicInfo> academicInfoList) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(FILE_PATH))) {
            for (AcademicInfo info : academicInfoList) {
                writer.write("학사담당자번호: " + info.getAcademicNumber() + "\n");
                writer.write("이름: " + info.getName() + "\n");
                writer.write("생년월일: " + info.getBirthDate() + "\n");
                writer.write("휴대폰: " + info.getPhone() + "\n");
                writer.write("비밀번호: " + info.getPassword() + "\n\n"); // 비밀번호 저장
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 저장 오류: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String generateNewAcademicNumber(List<AcademicInfo> academicInfoList) {
        int maxNumber = academicInfoList.stream()
                .mapToInt(info -> Integer.parseInt(info.getAcademicNumber().substring(1)))
                .max()
                .orElse(0);
        return String.format("H%03d", maxNumber + 1);
    }
    private void info_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_refreshActionPerformed
        // S_info 초기화
        DefaultTableModel infoModel = (DefaultTableModel) S_info.getModel();
        infoModel.setRowCount(0);

        String filePath = Paths.get(System.getProperty("user.home"), "data", "Academic_info.txt").toString();

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            String studentNumber = "", name = "", birthDate = "", phone = "";

            while ((line = reader.readLine()) != null) {
                line = line.trim();

                if (line.startsWith("학사담당자번호: ")) {
                    studentNumber = line.substring(8).trim(); // 공백 제거 포함
                } else if (line.startsWith("이름: ")) {
                    name = line.substring(4);
                } else if (line.startsWith("생년월일: ")) {
                    birthDate = line.substring(6);
                } else if (line.startsWith("휴대폰: ")) {
                    phone = line.substring(5);
                } else if (line.isEmpty()) {
                    // 모든 필드가 채워진 경우 S_info에 추가
                    if (!studentNumber.isEmpty() && !name.isEmpty()
                            && !birthDate.isEmpty() && !phone.isEmpty()) {
                        infoModel.addRow(new Object[]{name, studentNumber, birthDate, phone});
                    }
                    // 데이터 초기화
                    studentNumber = name = birthDate = phone = "";
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일을 읽는 중 오류가 발생했습니다.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_info_refreshActionPerformed

    private void birthlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthlastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthlastActionPerformed

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed
// 입력 필드를 초기화하는 메서드

    private void clearInputFields() {
        Name.setText("");           // 이름
        Phone.setText("");          // 전화번호
        birth.setText("");          // 주민등록번호 앞자리
        birthlast.setText(""); //주민등록번호 뒷자리
    }

    private void updateStudentInfoInFile(String updatedName, String updatedStudentNumber, String updatedDepartment,
            String updatedGrade, String updatedBirthDate, String updatedPhone) {
        String filePath = Paths.get(System.getProperty("user.home"), "data", "Academic_info.txt").toString();
        StringBuilder updatedContent = new StringBuilder();

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            String studentNumber = "", name = "", birthDate = "", phone = "";
            boolean isStudentFound = false;

            while ((line = reader.readLine()) != null) {
                line = line.trim();

                if (line.startsWith("학사담당자번호: ")) {
                    studentNumber = line.substring(8).trim(); // 공백 제거 포함
                } else if (line.startsWith("이름: ")) {
                    name = line.substring(4);
                } else if (line.startsWith("생년월일: ")) {
                    birthDate = line.substring(6);
                } else if (line.startsWith("휴대폰: ")) {
                    phone = line.substring(5);
                } else if (line.isEmpty()) {
                    // 기존 데이터와 입력된 데이터를 비교해 일치하는 학생 찾기
                    if (name.equals(updatedName) && studentNumber.equals(updatedStudentNumber)) {
                        isStudentFound = true;

                        // 수정된 값으로 덮어쓰기 (수정하지 않은 값은 기존 값을 유지)
                        updatedContent.append("학사담당자번호: ").append(updatedStudentNumber).append("\n");
                        updatedContent.append("이름: ").append(updatedName).append("\n");
                        updatedContent.append("생년월일: ").append(updatedBirthDate.isEmpty() ? birthDate : updatedBirthDate).append("\n");
                        updatedContent.append("휴대폰: ").append(updatedPhone.isEmpty() ? phone : updatedPhone).append("\n\n");
                    } else {
                        // 기존 데이터 유지
                        updatedContent.append("학사담당자번호: ").append(studentNumber).append("\n");
                        updatedContent.append("이름: ").append(name).append("\n");
                        updatedContent.append("생년월일: ").append(birthDate).append("\n");
                        updatedContent.append("휴대폰: ").append(phone).append("\n\n");
                    }
                }
            }

            if (!isStudentFound) {
                JOptionPane.showMessageDialog(this, "수정할 학사 담당자 정보를 찾을 수 없습니다.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일을 읽는 중 오류가 발생했습니다.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // 파일에 수정된 내용 덮어쓰기
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
            writer.write(updatedContent.toString());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일을 저장하는 중 오류가 발생했습니다.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Before;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Phone;
    private javax.swing.JTable S_info;
    private javax.swing.JTable S_list;
    private javax.swing.JTextField S_search;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField birth;
    private javax.swing.JLabel birthdate;
    private javax.swing.JTextField birthlast;
    private javax.swing.JButton info_refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modify;
    private javax.swing.JLabel name;
    private javax.swing.JComboBox<String> numberBox;
    private javax.swing.JLabel phone;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JButton search_button;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
