/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.UIS.ChangePassword;

import deu.UIS.Login.UserSession;
import javax.swing.*;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author YangJinWon
 */
public class ChangePassword extends javax.swing.JFrame {

    private static final String STUDENT_INFO_PATH = Paths.get(System.getProperty("user.home"), "data", "student_info.txt").toString();
    private static final String PROFESSOR_INFO_PATH = Paths.get(System.getProperty("user.home"), "data", "professor_info.txt").toString();
    private static final String ACADEMIC_INFO_PATH = Paths.get(System.getProperty("user.home"), "data", "Academic_info.txt").toString();
    private static final String CLASS_MANAGER_PATH = Paths.get(System.getProperty("user.home"), "data", "Class_Manager.txt").toString();

    // 파일 경로 목록
    private static final String[] FILE_PATHS = {STUDENT_INFO_PATH, PROFESSOR_INFO_PATH, ACADEMIC_INFO_PATH, CLASS_MANAGER_PATH};
    private final String loggedInUserId;

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
        this.loggedInUserId = UserSession.getInstance().getUserId(); // 로그인한 유저의 ID 가져오기
        configureEnterKey();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PresentPassword = new javax.swing.JTextField();
        ChangePassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("비밀번호 변경 페이지");

        PresentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresentPasswordActionPerformed(evt);
            }
        });

        ChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordActionPerformed(evt);
            }
        });

        jLabel2.setText("현재 비밀번호");

        jLabel3.setText("변경할 비밀번호");

        Save.setText("저장");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Save)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PresentPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(ChangePassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PresentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(Save)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configureEnterKey() {
        java.awt.event.KeyAdapter enterKeyListener = new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    Save.doClick(); // 저장 버튼 클릭
                }
            }
        };
        PresentPassword.addKeyListener(enterKeyListener);
        ChangePassword.addKeyListener(enterKeyListener);
    }

    private void PresentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresentPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresentPasswordActionPerformed

    private void ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangePasswordActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        String presentPassword = PresentPassword.getText().trim();
    String newPassword = ChangePassword.getText().trim();

    if (presentPassword.isEmpty() || newPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "모든 필드를 입력해주세요.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    boolean isPasswordUpdated = false;
    String loggedInUserId = UserSession.getInstance().getUserId(); // 로그인된 사용자 ID

    // 파일 목록 순회
    for (String filePath : FILE_PATHS) {
        try {
            List<String> lines = Files.readAllLines(Paths.get(filePath)); // 파일 전체 읽기
            List<String> updatedLines = new ArrayList<>();

            boolean isUserFound = false;
            boolean isPasswordMatched = false;

            for (int i = 0; i < lines.size(); i++) {
                String line = lines.get(i);

                // 현재 줄에 ID가 포함되어 있는지 확인
                if (line.startsWith("학번:") || line.startsWith("교수번호:") || line.startsWith("학사담당자번호:") || line.startsWith("수업담당자번호:")) {
                    String id = line.split(":")[1].trim();
                    if (id.equals(loggedInUserId)) {
                        isUserFound = true; // 사용자 확인
                    }
                }

                // 현재 줄에 비밀번호가 포함되어 있는지 확인
                if (isUserFound && line.startsWith("비밀번호:")) {
                    String currentPasswordInFile = line.split(":")[1].trim();
                    if (currentPasswordInFile.equals(presentPassword)) {
                        // 비밀번호를 새 비밀번호로 변경
                        updatedLines.add("비밀번호: " + newPassword);
                        isPasswordMatched = true;
                        isPasswordUpdated = true;
                    } else {
                        updatedLines.add(line);
                    }
                    isUserFound = false; // 사용자 처리 완료 후 초기화
                } else {
                    updatedLines.add(line);
                }
            }

            // 파일에 다시 쓰기
            if (isPasswordMatched) {
                Files.write(Paths.get(filePath), updatedLines);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 처리 중 오류가 발생했습니다: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    if (isPasswordUpdated) {
        JOptionPane.showMessageDialog(this, "비밀번호가 성공적으로 변경되었습니다.");
        PresentPassword.setText("");
        ChangePassword.setText("");
        dispose(); // 창 닫기
    } else {
        JOptionPane.showMessageDialog(this, "현재 비밀번호가 일치하지 않습니다.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChangePassword;
    private javax.swing.JTextField PresentPassword;
    private javax.swing.JButton Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
