/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.UIS.AcademicManager;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YangJinWon
 */
public class S_Academic_Management extends javax.swing.JFrame {

    private final StudentFileManager studentFileManager;
    private final StudentTableManager tableManager;

    public S_Academic_Management() {
        initComponents();
        String filePath = Paths.get(System.getProperty("user.home"), "data", "student_info.txt").toString();
        studentFileManager = new StudentFileManager(filePath);
        tableManager = new StudentTableManager((DefaultTableModel) S_list.getModel());
        loadStudentInfo();
        addMouseListenerToSList(); // 반드시 호출
    }
    // 학생 정보를 파일에서 불러와 테이블에 추가하는 메서드

    private void loadStudentInfo() {
        try {
            List<Student> students = studentFileManager.readStudents();
            tableManager.loadStudentsToTable(students);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "학생 정보를 불러오는 중 오류가 발생했습니다: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void addMouseListenerToSList() {
        S_list.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int selectedRow = S_list.getSelectedRow();
                if (selectedRow != -1) {
                    String name = (String) S_list.getValueAt(selectedRow, 0);
                    String studentNumber = (String) S_list.getValueAt(selectedRow, 1);
                    String department = (String) S_list.getValueAt(selectedRow, 2);

                    if (name != null && studentNumber != null && department != null) {
                        populateStudentDetails(department, studentNumber, name);
                    }
                }
            }
        });
    }

private void populateStudentDetails(String department, String studentNumber, String name) {
    String filePath = Paths.get(System.getProperty("user.home"), "data", "student_info.txt").toString();
        DefaultTableModel infoModel = new DefaultTableModel(new String[]{"이름", "학번", "학과", "학년", "생년월일", "휴대폰"}, 0);
        S_info.setModel(infoModel);

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line, departmentFile = "", studentNumberFile = "", nameFile = "", gradeFile = "", birthDateFile = "", phoneFile = "";

            while ((line = reader.readLine()) != null) {
                line = line.trim();

                if (line.startsWith("학과: ")) departmentFile = line.substring(4).trim();
                if (line.startsWith("학번: ")) studentNumberFile = line.substring(4).trim();
                if (line.startsWith("이름: ")) nameFile = line.substring(4).trim();
                if (line.startsWith("학년: ")) gradeFile = line.substring(4).trim();
                if (line.startsWith("생년월일: ")) birthDateFile = line.substring(6).trim();
                if (line.startsWith("휴대폰: ")) phoneFile = line.substring(5).trim();

                if (!departmentFile.isEmpty() && !studentNumberFile.isEmpty() && !nameFile.isEmpty()
                        && !gradeFile.isEmpty() && !birthDateFile.isEmpty() && !phoneFile.isEmpty()) {
                    if (departmentFile.equals(department) && studentNumberFile.equals(studentNumber) && nameFile.equals(name)) {
                        infoModel.addRow(new Object[]{nameFile, studentNumberFile, departmentFile, gradeFile, birthDateFile, phoneFile});
                        break;
                    }
                    departmentFile = studentNumberFile = nameFile = gradeFile = birthDateFile = phoneFile = "";
                }
            }
            S_info.repaint();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "학생 정보 검색 중 오류가 발생했습니다: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        department = new javax.swing.JLabel();
        grade = new javax.swing.JLabel();
        birthdate = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numberBox = new javax.swing.JComboBox<>();
        Name = new javax.swing.JTextField();
        gradeBox = new javax.swing.JComboBox<>();
        birth = new javax.swing.JTextField();
        birthlast = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        S_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        search_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        Before = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        S_list = new javax.swing.JTable();
        Delete = new javax.swing.JButton();
        modify = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        S_info = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        save = new javax.swing.JButton();
        info_refresh = new javax.swing.JButton();
        DepartmentComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        Title.setText("학생 학사 관리 페이지");

        title.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        title.setText("학생 정보 입력");

        name.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        name.setText("이름");

        department.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        department.setText("학과");

        grade.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        grade.setText("학년");

        birthdate.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        birthdate.setText("주민등록번호");

        phone.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        phone.setText("휴대폰");

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        jLabel1.setText("학생 정보 검색");

        numberBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "학번", "이름" }));
        numberBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBoxActionPerformed(evt);
            }
        });

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        gradeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1학년", "2학년", "3학년", "4학년" }));
        gradeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeBoxActionPerformed(evt);
            }
        });

        birth.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        birth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthActionPerformed(evt);
            }
        });

        birthlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthlastActionPerformed(evt);
            }
        });

        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });

        S_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_searchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        jLabel2.setText("학생 정보");

        search_button.setText("검색");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        jLabel3.setText("학생 목록");

        Add.setText("추가");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Before.setText("이전");
        Before.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeforeActionPerformed(evt);
            }
        });

        S_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "이름", "학번", "학과"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(S_list);

        Delete.setText("삭제");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        modify.setText("수정");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });

        S_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "이름", "학번", "학과", "학년", "생년월일", "휴대폰"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(S_info);

        refresh.setText("새로고침");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        save.setText("저장");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        info_refresh.setText("새로고침");
        info_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                info_refreshActionPerformed(evt);
            }
        });

        DepartmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "컴퓨터소프트웨어공학과", "전산학과", "전자공학과", "화학공학과", "기계공학과", "항공우주공학과" }));
        DepartmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartmentComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(info_refresh)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(Add)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Before))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(phone)
                                                .addComponent(birthdate)
                                                .addComponent(department))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Phone)
                                                .addComponent(gradeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Name)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(birth, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(birthlast))
                                                .addComponent(DepartmentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(2, 2, 2)))
                                    .addComponent(grade)
                                    .addComponent(title)
                                    .addComponent(name))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(numberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(S_search, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(modify)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(save)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Delete))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(refresh))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(Title)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(S_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search_button)
                            .addComponent(numberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(refresh))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(department)
                                    .addComponent(DepartmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(grade)
                                    .addComponent(gradeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(birthdate)
                                    .addComponent(birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(birthlast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phone))
                                .addGap(2, 2, 2))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Add)
                            .addComponent(Before)
                            .addComponent(modify)
                            .addComponent(save)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Delete)
                            .addComponent(info_refresh))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed

    private void numberBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberBoxActionPerformed

    private void gradeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeBoxActionPerformed

    private void S_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_S_searchActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        String keyword = S_search.getText().trim(); // 검색 필드에서 키워드를 가져옵니다.
        String searchType = (String) numberBox.getSelectedItem(); // numberBox에서 선택된 값을 가져옵니다.

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "검색어를 입력해주세요.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String filePath = Paths.get(System.getProperty("user.home"), "data", "student_info.txt").toString();
        DefaultTableModel model = (DefaultTableModel) S_list.getModel();
        model.setRowCount(0); // 테이블 초기화

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            String department = "", studentNumber = "", name = "";

            while ((line = reader.readLine()) != null) {
                line = line.trim();

                if (line.startsWith("학과: ")) {
                    department = line.substring(4);
                } else if (line.startsWith("학번: ")) {
                    studentNumber = line.substring(4);
                } else if (line.startsWith("이름: ")) {
                    name = line.substring(4);
                } else if (line.isEmpty() && !department.isEmpty() && !studentNumber.isEmpty() && !name.isEmpty()) {
                    // 검색 타입에 따라 검색
                    boolean matches = false;
                    if ("학번".equals(searchType)) {
                        matches = keyword.equals(studentNumber); // 학번 검색
                    } else if ("이름".equals(searchType)) {
                        matches = keyword.equalsIgnoreCase(name); // 이름 검색 (대소문자 무시)
                    }

                    if (matches) {
                        model.addRow(new Object[]{name, studentNumber, department});
                    }
                    // 초기화
                    department = studentNumber = name = "";
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "학생 정보 검색 중 오류가 발생했습니다.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "검색 결과가 없습니다.", "검색", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_search_buttonActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        try {
        String name = Name.getText().trim();
        String department = (String) DepartmentComboBox.getSelectedItem();
        String grade = (String) gradeBox.getSelectedItem();
        String phone = Phone.getText().trim();
        String birthDate = birth.getText().trim() + "-" + birthlast.getText().trim();

        // 입력값 유효성 검증
        S_ValidationUtils.validateInputFields(name, department, grade, phone, birthDate);

        // 학생 목록 불러오기
        List<Student> students = studentFileManager.readStudents();
        String newStudentNumber = generateNewStudentNumber(students);

        // 생년월일 뒷자리 7자리로 비밀번호 설정
        String[] birthParts = birthDate.split("-");
        String password = (birthParts.length == 2) ? birthParts[1] : "생년월일 형식 오류";

        // 새 학생 추가
        Student newStudent = new Student(name, newStudentNumber, department, grade, birthDate, phone);
        newStudent.setPassword(password); // 비밀번호 설정
        students.add(newStudent);

        // 파일 저장 및 테이블 갱신
        studentFileManager.writeStudents(students);
        tableManager.loadStudentsToTable(students);

        JOptionPane.showMessageDialog(this, "학생 정보가 추가되었습니다.");
        clearInputFields();
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "파일 처리 오류: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_AddActionPerformed
    private String generateNewStudentNumber(List<Student> students) {
        int maxNumber = students.stream()
                .mapToInt(student -> Integer.parseInt(student.getStudentNumber().substring(1)))
                .max()
                .orElse(0);
        return String.format("S%03d", maxNumber + 1);
    }
    private void BeforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeforeActionPerformed
        // TODO add your handling code here:
        dispose();

        new A_Main().setVisible(true);
    }//GEN-LAST:event_BeforeActionPerformed

    private void birthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
int selectedRow = S_list.getSelectedRow();

    if (selectedRow != -1) {
        DefaultTableModel model = (DefaultTableModel) S_list.getModel();
        String selectedStudentNumber = (String) model.getValueAt(selectedRow, 1);

        String filePath = Paths.get(System.getProperty("user.home"), "data", "student_info.txt").toString();
        StringBuilder updatedContent = new StringBuilder();

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            String department = "", studentNumber = "", name = "", grade = "", birthDate = "", phone = "", password = "";

            while ((line = reader.readLine()) != null) {
                line = line.trim();

                if (line.startsWith("학과: ")) department = line.substring(4);
                else if (line.startsWith("학번: ")) studentNumber = line.substring(4);
                else if (line.startsWith("이름: ")) name = line.substring(4);
                else if (line.startsWith("학년: ")) grade = line.substring(4);
                else if (line.startsWith("생년월일: ")) birthDate = line.substring(6);
                else if (line.startsWith("휴대폰: ")) phone = line.substring(5);
                else if (line.startsWith("비밀번호: ")) password = line.substring(6);

                if (line.isEmpty() && !department.isEmpty() && !studentNumber.isEmpty() && !name.isEmpty()
                        && !grade.isEmpty() && !birthDate.isEmpty() && !phone.isEmpty() && !password.isEmpty()) {

                    if (!studentNumber.equals(selectedStudentNumber)) {
                        updatedContent.append("학과: ").append(department).append("\n");
                        updatedContent.append("학번: ").append(studentNumber).append("\n");
                        updatedContent.append("이름: ").append(name).append("\n");
                        updatedContent.append("학년: ").append(grade).append("\n");
                        updatedContent.append("생년월일: ").append(birthDate).append("\n");
                        updatedContent.append("휴대폰: ").append(phone).append("\n");
                        updatedContent.append("비밀번호: ").append(password).append("\n\n");
                    }
                    department = studentNumber = name = grade = birthDate = phone = password = ""; // 초기화
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 읽기 중 오류가 발생했습니다.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
            writer.write(updatedContent.toString());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "파일 저장 중 오류가 발생했습니다.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        model.removeRow(selectedRow);
        JOptionPane.showMessageDialog(this, "선택된 학생 정보가 삭제되었습니다.");
    } else {
        JOptionPane.showMessageDialog(this, "삭제할 학생을 선택해 주세요.", "Warning", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_DeleteActionPerformed

    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        // 선택된 학생 정보가 없으면 경고 메시지
        int selectedRow = S_list.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "수정할 학생을 선택해주세요.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 선택된 행에서 기본 정보를 가져옵니다.
        String selectedName = (String) S_list.getValueAt(selectedRow, 0);         // 이름
        String selectedStudentNumber = (String) S_list.getValueAt(selectedRow, 1); // 학번
        String selectedDepartment = (String) S_list.getValueAt(selectedRow, 2);    // 학과

        // 파일에서 선택된 학생의 세부 정보를 가져와서 입력 필드에 채웁니다.
        String filePath = Paths.get(System.getProperty("user.home"), "data", "student_info.txt").toString();

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line;
            String department = "", studentNumber = "", name = "", grade = "", birthDate = "", phone = "";

            while ((line = reader.readLine()) != null) {
                line = line.trim();

                if (line.startsWith("학과: ")) {
                    department = line.substring(4);
                } else if (line.startsWith("학번: ")) {
                    studentNumber = line.substring(4);
                } else if (line.startsWith("이름: ")) {
                    name = line.substring(4);
                } else if (line.startsWith("학년: ")) {
                    grade = line.substring(4);
                } else if (line.startsWith("생년월일: ")) {
                    birthDate = line.substring(6);
                } else if (line.startsWith("휴대폰: ")) {
                    phone = line.substring(5);
                } else if (line.isEmpty() && name.equals(selectedName) && studentNumber.equals(selectedStudentNumber) && department.equals(selectedDepartment)) {
                    // 선택된 학생과 일치하는 정보를 찾았을 때 입력 필드에 채우기

                    Name.setText(name);
                    // ComboBox에서 해당 학과 선택
                    DepartmentComboBox.setSelectedItem(department);
                    gradeBox.setSelectedItem(grade);
                    birth.setText(birthDate);
                    Phone.setText(phone);
                    // 주민등록번호를 앞 6자리와 뒤 7자리로 나눔
                    if (birthDate.length() == 14) { // 주민등록번호 형식 확인 (앞 6 + "-" + 뒤 7)
                        String[] parts = birthDate.split("-");
                        if (parts.length == 2) {
                            birth.setText(parts[0]);     // 앞 6자리
                            birthlast.setText(parts[1]); // 뒤 7자리
                        }
                    } else {
                        birth.setText(birthDate); // 형식이 맞지 않을 경우 전체 입력
                    }

                    Phone.setText(phone);
                    break;
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "교수 정보를 불러오는 중 오류가 발생했습니다.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modifyActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // 학생 정보를 다시 불러와서 S_list 테이블을 새로 갱신합니다.
        loadStudentInfo();
    }//GEN-LAST:event_refreshActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
     int selectedRow = S_list.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "수정할 학생을 선택해주세요.", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String studentNumber = (String) S_list.getValueAt(selectedRow, 1);

    try {
        List<Student> students = studentFileManager.readStudents(); // 학생 목록 읽기
        for (Student student : students) {
            if (student.getStudentNumber().equals(studentNumber)) {
                // 유효성 검증
                String updatedName = Name.getText().trim();
                String updatedDepartment = (String) DepartmentComboBox.getSelectedItem();
                String updatedGrade = (String) gradeBox.getSelectedItem();
                String updatedPhone = Phone.getText().trim();
                String updatedBirthDatePart1 = birth.getText().trim(); // 앞 6자리
                String updatedBirthDatePart2 = birthlast.getText().trim(); // 뒤 7자리

                if (updatedName.isEmpty() || updatedDepartment.isEmpty() || updatedGrade.isEmpty() || 
                    updatedPhone.isEmpty() || updatedBirthDatePart1.isEmpty() || updatedBirthDatePart2.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "모든 필드를 입력해야 합니다.", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                if (!updatedBirthDatePart1.matches("\\d{6}") || !updatedBirthDatePart2.matches("\\d{7}")) {
                    JOptionPane.showMessageDialog(this, "생년월일 형식이 잘못되었습니다. (예: 123456-1234567)", "Warning", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                // 생년월일 통합
                String updatedBirthDate = updatedBirthDatePart1 + "-" + updatedBirthDatePart2;

                // 학생 정보 수정
                student.setName(updatedName);
                student.setDepartment(updatedDepartment);
                student.setGrade(updatedGrade);
                student.setBirthDate(updatedBirthDate);
                student.setPhone(updatedPhone);

                // 생년월일 뒷자리 7자리로 비밀번호 설정
                student.setPassword(updatedBirthDatePart2);

                break;
            }
        }
        studentFileManager.writeStudents(students); // 파일에 수정된 학생 정보 저장

        // 테이블 갱신
        tableManager.loadStudentsToTable(students);

        // 정보 저장 성공 메시지
        JOptionPane.showMessageDialog(this, "학생 정보가 수정되었습니다.");

        // 입력 필드 초기화
        clearInputFields();

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "파일 처리 오류: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "알 수 없는 오류가 발생했습니다.\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_saveActionPerformed

    private void info_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_info_refreshActionPerformed
        String filePath = Paths.get(System.getProperty("user.home"), "data", "student_info.txt").toString();
        DefaultTableModel infoModel = new DefaultTableModel(new String[]{"이름", "학번", "학과", "학년", "생년월일", "휴대폰"}, 0);
        S_info.setModel(infoModel);

        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            String line, department = "", studentNumber = "", name = "", grade = "", birthDate = "", phone = "";

            while ((line = reader.readLine()) != null) {
                line = line.trim();

                if (line.startsWith("학과: ")) department = line.substring(4).trim();
                if (line.startsWith("학번: ")) studentNumber = line.substring(4).trim();
                if (line.startsWith("이름: ")) name = line.substring(4).trim();
                if (line.startsWith("학년: ")) grade = line.substring(4).trim();
                if (line.startsWith("생년월일: ")) birthDate = line.substring(6).trim();
                if (line.startsWith("휴대폰: ")) phone = line.substring(5).trim();

                if (!department.isEmpty() && !studentNumber.isEmpty() && !name.isEmpty()
                        && !grade.isEmpty() && !birthDate.isEmpty() && !phone.isEmpty()) {
                    infoModel.addRow(new Object[]{name, studentNumber, department, grade, birthDate, phone});
                    department = studentNumber = name = grade = birthDate = phone = "";
                }
            }
            S_info.repaint();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "학생 정보를 새로고침하는 중 오류가 발생했습니다: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_info_refreshActionPerformed

    private void birthlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthlastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthlastActionPerformed

    private void DepartmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartmentComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartmentComboBoxActionPerformed
// 입력 필드를 초기화하는 메서드

    private void clearInputFields() {
        Name.setText("");
        DepartmentComboBox.setSelectedIndex(0);
        gradeBox.setSelectedIndex(0);
        Phone.setText("");
        birth.setText("");
        birthlast.setText("");
    }

 private void updateStudentInfoInFile(String updatedName, String updatedStudentNumber, String updatedDepartment,
                                     String updatedGrade, String updatedBirthDate, String updatedPhone) {
    String filePath = Paths.get(System.getProperty("user.home"), "data", "student_info.txt").toString();
    StringBuilder updatedContent = new StringBuilder();
    boolean isStudentFound = false;

    try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
        String line;
        String department = "", studentNumber = "", name = "", grade = "", birthDate = "", phone = "", password = "";

        while ((line = reader.readLine()) != null) {
            line = line.trim();

            if (line.startsWith("학과: ")) department = line.substring(4);
            else if (line.startsWith("학번: ")) studentNumber = line.substring(4);
            else if (line.startsWith("이름: ")) name = line.substring(4);
            else if (line.startsWith("학년: ")) grade = line.substring(4);
            else if (line.startsWith("생년월일: ")) birthDate = line.substring(6);
            else if (line.startsWith("휴대폰: ")) phone = line.substring(5);
            else if (line.startsWith("비밀번호: ")) password = line.substring(6);

            if (line.isEmpty() && !department.isEmpty() && !studentNumber.isEmpty() && !name.isEmpty()
                    && !grade.isEmpty() && !birthDate.isEmpty() && !phone.isEmpty() && !password.isEmpty()) {

                if (name.equals(updatedName) && studentNumber.equals(updatedStudentNumber)) {
                    isStudentFound = true;
                    String updatedPassword = updatedBirthDate.split("-")[1]; // 생년월일 뒷자리 7자리
                    updatedContent.append("학과: ").append(updatedDepartment.isEmpty() ? department : updatedDepartment).append("\n");
                    updatedContent.append("학번: ").append(updatedStudentNumber).append("\n");
                    updatedContent.append("이름: ").append(updatedName).append("\n");
                    updatedContent.append("학년: ").append(updatedGrade.isEmpty() ? grade : updatedGrade).append("\n");
                    updatedContent.append("생년월일: ").append(updatedBirthDate.isEmpty() ? birthDate : updatedBirthDate).append("\n");
                    updatedContent.append("휴대폰: ").append(updatedPhone.isEmpty() ? phone : updatedPhone).append("\n");
                    updatedContent.append("비밀번호: ").append(updatedPassword).append("\n\n");
                } else {
                    updatedContent.append("학과: ").append(department).append("\n");
                    updatedContent.append("학번: ").append(studentNumber).append("\n");
                    updatedContent.append("이름: ").append(name).append("\n");
                    updatedContent.append("학년: ").append(grade).append("\n");
                    updatedContent.append("생년월일: ").append(birthDate).append("\n");
                    updatedContent.append("휴대폰: ").append(phone).append("\n");
                    updatedContent.append("비밀번호: ").append(password).append("\n\n");
                }

                department = studentNumber = name = grade = birthDate = phone = password = ""; // 초기화
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "파일을 읽는 중 오류가 발생했습니다.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!isStudentFound) {
        JOptionPane.showMessageDialog(this, "수정할 학생 정보를 찾을 수 없습니다.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
        writer.write(updatedContent.toString());
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "파일을 저장하는 중 오류가 발생했습니다.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S_Academic_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S_Academic_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S_Academic_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S_Academic_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S_Academic_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Before;
    private javax.swing.JButton Delete;
    private javax.swing.JComboBox<String> DepartmentComboBox;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Phone;
    private javax.swing.JTable S_info;
    private javax.swing.JTable S_list;
    private javax.swing.JTextField S_search;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField birth;
    private javax.swing.JLabel birthdate;
    private javax.swing.JTextField birthlast;
    private javax.swing.JLabel department;
    private javax.swing.JLabel grade;
    private javax.swing.JComboBox<String> gradeBox;
    private javax.swing.JButton info_refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modify;
    private javax.swing.JLabel name;
    private javax.swing.JComboBox<String> numberBox;
    private javax.swing.JLabel phone;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JButton search_button;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
