/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.UIS.Student;
//dsada

/**
 *
 * @author YangJinWon
 */
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Student_Management extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Student_Management() {
        initComponents();
        loadDataFromFile();  // 텍스트 파일에서 데이터를 읽어오는 메서드

        S_ReqInfo.getColumnModel().getColumn(0).setCellRenderer(new ButtonRenderer());
        S_ReqInfo.getColumnModel().getColumn(0).setCellEditor(new ButtonEditor(new JCheckBox()));
    }   // "신청"버튼이 들어가는 열에 버튼랜더러와 버튼에디터 설정

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        S_PreCourseTitle = new javax.swing.JLabel();
        S_RequestTitle = new javax.swing.JLabel();
        S_RequestTitle1 = new javax.swing.JLabel();
        S_Request = new javax.swing.JScrollPane();
        S_ReqInfo = new javax.swing.JTable();
        S_PreCourse = new javax.swing.JScrollPane();
        S_PreCouInfo = new javax.swing.JTable();
        S_Timetable = new javax.swing.JScrollPane();
        S_TimeInfo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("맑은 고딕", 0, 16)); // NOI18N
        Title.setText("학생 수강신청 페이지");

        Back.setText("뒤로가기");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        S_PreCourseTitle.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        S_PreCourseTitle.setText("  수강 현황");

        S_RequestTitle.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        S_RequestTitle.setText("  개설강좌");

        S_RequestTitle1.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        S_RequestTitle1.setText("  시간표 현황");

        S_ReqInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "신청", "과목번호", "과목명", "학점/시간", "담당교수", "강의실(시간)", "원격여부"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        S_ReqInfo.setRowHeight(25);
        S_ReqInfo.setShowHorizontalLines(true);
        S_ReqInfo.setShowVerticalLines(true);
        S_Request.setViewportView(S_ReqInfo);

        S_PreCouInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "과목번호", "과목명", "학점/시간", "담당교수", "강의실(시간)", "원격여부"
            }
        ));
        S_PreCouInfo.setRowHeight(25);
        S_PreCouInfo.setShowHorizontalLines(true);
        S_PreCouInfo.setShowVerticalLines(true);
        S_PreCourse.setViewportView(S_PreCouInfo);

        S_TimeInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1교시", null, null, null, null, null},
                {"2교시", null, null, null, null, null},
                {"3교시", null, null, null, null, null},
                {"4교시", null, null, null, null, null},
                {"5교시", null, null, null, null, null},
                {"6교시", null, null, null, null, null},
                {"7교시", null, null, null, null, null},
                {"8교시", null, null, null, null, null},
                {"9교시", null, null, null, null, null},
                {"10교시", null, null, null, null, null}
            },
            new String [] {
                "", "월요일", "화요일", "수요일", "목요일", "금요일"
            }
        ));
        S_TimeInfo.setRowHeight(27);
        S_TimeInfo.setShowGrid(true);
        S_Timetable.setViewportView(S_TimeInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(S_PreCourse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(S_RequestTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(S_Request, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                        .addComponent(S_PreCourseTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(Back))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(S_RequestTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(S_Timetable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(391, 391, 391)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(S_RequestTitle)
                    .addComponent(S_RequestTitle1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(S_Request, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(S_PreCourseTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(S_PreCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(S_Timetable, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        dispose();
        new S_Main().setVisible(true); //뒤로가기
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Student_Management().setVisible(true);
        });
    }

    private void loadDataFromFile() {
        DefaultTableModel model = (DefaultTableModel) S_ReqInfo.getModel(); // 테이블 모델 가져오기
        
        model.setRowCount(0);   //기존 데이터 초기화  
        
        try (BufferedReader br = new BufferedReader(new FileReader("S_Course.txt"))) {
            String line;

            while ((line = br.readLine()) != null) {
                line = line.trim(); // 앞뒤 공백 제거
                if (line.isEmpty()) {
                    continue; // 빈 줄 건너뛰기
                }

                String[] data = line.split(","); // 쉼표로 구분된 데이터 분리

                if (data.length == 6) { // 필요한 열 개수만 처리
                    // 테이블에 데이터 추가
                    model.addRow(new Object[]{"신청", data[0], data[1], data[2], data[3], data[4], data[5]});
                } else {
                    System.err.println("잘못된 데이터 형식: " + line);
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "파일을 읽는 도중 오류가 발생했습니다: " + e.getMessage());
        }
    }

    //버튼랜더러
    class ButtonRenderer extends JButton implements TableCellRenderer {

        public ButtonRenderer() {
            setOpaque(true);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setText("신청");    // 버튼 텍스트
            return this;
        }
    }

    //버튼에디터
    class ButtonEditor extends DefaultCellEditor {

        protected JButton button;
        private boolean isPushed;

        public ButtonEditor(JCheckBox checkBox) {
            super(checkBox);
            button = new JButton();
            button.setOpaque(true);
            button.addActionListener(e -> fireEditingStopped());    //클릭시 편집 종료 이벤트 발생
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            button.setText("신청"); //버튼 텍스트
            isPushed = true;
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            if (isPushed) { //버튼 입력시 실행할 작업
                JOptionPane.showMessageDialog(null, "수강 신청이 완료되었습니다.");
            }
            isPushed = false;   //클릭 상태 초기화
            return "신청";
        }

        @Override
        public boolean stopCellEditing() {
            isPushed = false;
            return super.stopCellEditing();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTable S_PreCouInfo;
    private javax.swing.JScrollPane S_PreCourse;
    private javax.swing.JLabel S_PreCourseTitle;
    private javax.swing.JTable S_ReqInfo;
    private javax.swing.JScrollPane S_Request;
    private javax.swing.JLabel S_RequestTitle;
    private javax.swing.JLabel S_RequestTitle1;
    private javax.swing.JTable S_TimeInfo;
    private javax.swing.JScrollPane S_Timetable;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
