/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.UIS.Student;

import deu.UIS.Login.UserSession;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 *
 * @author YangJinWon
 */
public class TimeTable extends javax.swing.JFrame {

    private static final String STUDENT_COURSE_FILE_PATH = Paths.get(System.getProperty("user.home"), "data", "student_courses.txt").toString();

    /**
     * Creates new form TimeTable
     */
    public TimeTable() {
        initComponents();
        loadTimeTable();  // Load data into timetable

    }
 private void loadTimeTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String loggedInStudentId = UserSession.getInstance().getUserId();

        try (BufferedReader reader = new BufferedReader(new FileReader(STUDENT_COURSE_FILE_PATH))) {
            String line;

            while ((line = reader.readLine()) != null) {
                Map<String, String> dataMap = parseLineToMap(line);

                String studentId = dataMap.get("아이디");
                if (loggedInStudentId.equals(studentId)) {
                    String courseName = dataMap.get("강의 이름");
                    String day = dataMap.get("요일");
                    String time = dataMap.get("시간");

                    if (courseName != null && day != null && time != null) {
                        updateTableForStudent(day, time, courseName);
                    }
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private Map<String, String> parseLineToMap(String line) {
        Map<String, String> dataMap = new HashMap<>();
        String[] fields = line.split(", ");

        for (String field : fields) {
            String[] keyValue = field.split(": ");
            if (keyValue.length == 2) {
                dataMap.put(keyValue[0].trim(), keyValue[1].trim());
            }
        }
        return dataMap;
    }

    private void updateTableForStudent(String day, String time, String courseName) {
        int col = getDayColumnIndex(day);
        int[] rows = getTimeSlotIndices(time);

        if (col == -1 || rows.length == 0) {
            return;
        }

        for (int row : rows) {
            if (row >= 0 && row < jTable1.getRowCount() && col >= 1 && col < jTable1.getColumnCount()) {
                Object existingValue = jTable1.getValueAt(row, col);
                String updatedValue = (existingValue == null || existingValue.toString().isEmpty())
                        ? courseName
                        : existingValue + " / " + courseName;

                jTable1.setValueAt(updatedValue, row, col);
            }
        }
    }

    private int[] getTimeSlotIndices(String time) {
        String[] slots = {
                "09:00 - 10:00", "10:00 - 11:00", "11:00 - 12:00",
                "12:00 - 13:00", "13:00 - 14:00", "14:00 - 15:00",
                "15:00 - 16:00", "16:00 - 17:00", "17:00 - 18:00"
        };

        List<Integer> indices = new ArrayList<>();
        if (time.contains("-")) {
            String start = time.split("-")[0].trim();
            String end = time.split("-")[1].trim();

            boolean inRange = false;

            for (int i = 0; i < slots.length; i++) {
                if (slots[i].startsWith(start)) {
                    inRange = true;
                }
                if (inRange) {
                    indices.add(i);
                }
                if (slots[i].endsWith(end)) {
                    break;
                }
            }
        }

        return indices.stream().mapToInt(i -> i).toArray();
    }

    private int getDayColumnIndex(String day) {
        Map<String, Integer> dayToColumn = Map.of(
                "월요일", 1,
                "화요일", 2,
                "수요일", 3,
                "목요일", 4,
                "금요일", 5
        );

        return dayToColumn.getOrDefault(day, -1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        before = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("시간표 조회");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"09:00 -10:00", null, null, null, null, null},
                {"10:00 - 11:00", null, null, null, null, null},
                {"11:00 - 12:00", null, null, null, null, null},
                {"12:00 - 13:00", null, null, null, null, null},
                {"13:00 - 14:00", null, null, null, null, null},
                {"14:00 - 15:00", null, null, null, null, null},
                {"15:00 - 16:00", null, null, null, null, null},
                {"16:00 - 17:00", null, null, null, null, null},
                {"17:00 - 18:00", null, null, null, null, null}
            },
            new String [] {
                "", "월요일", "화요일", "수요일", "목요일", "금요일"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        before.setText("이전");
        before.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beforeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(before)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(before)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beforeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beforeActionPerformed
        dispose();
        new S_Main().setVisible(true);
        
    }//GEN-LAST:event_beforeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimeTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton before;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
